import type { Metadata } from "next";
import "./globals.css";
import Background from "@/components/Background";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative min-h-screen text-white overflow-x-hidden">
        <Background />
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
